services:
  - name: web
    run_command: npm start  # Command to start your application
    environment_slug: node-js

    build:
      - name: Install and fix dependencies
        run: |
          npm audit fix --force
          npm install
      - name: Build application
        run: npm run build  # Customize if you have a build command