# .do/deploy.template.yaml

services:
  - name: web
    run_command: npm start
    environment_slug: node-js

    build:
      - name: Clear npm cache, install dependencies, and fix vulnerabilities
        run: |
          npm cache clean --force  # Clears the npm cache
          npm install
          npm audit fix --force
      - name: Build application
        run: npm run build
